const clients = [
  { id:1, firstName:"Judicaël" ,lastName:"Tether" },
  { id:2, firstName:"Agnès" ,lastName:"Beakes" },
  { id:3, firstName:"Mégane" ,lastName:"Duplan" },
  { id:4, firstName:"Noémie" ,lastName:"Ardy" },
  { id:5, firstName:"Alizée" ,lastName:"Rentcome" },
  { id:6, firstName:"Adélaïde" ,lastName:"Tooker" },
  { id:7, firstName:"Célestine" ,lastName:"Andreasson" },
  { id:8, firstName:"Eléonore" ,lastName:"Lydster" },
  { id:9, firstName:"Dana" ,lastName:"Loxston" },
  { id:10, firstName:"Mélodie" ,lastName:"Yellowlee" },
  { id:11, firstName:"Styrbjörn" ,lastName:"Stroban" },
  { id:12, firstName:"Angélique" ,lastName:"Pezey" },
  { id:13, firstName:"Nadège" ,lastName:"Slocket" },
  { id:14, firstName:"Eléonore" ,lastName:"Gregore" },
  { id:15, firstName:"Océanne" ,lastName:"Thistleton" },
  { id:16, firstName:"Stévina" ,lastName:"McKenney" },
  { id:17, firstName:"Magdalène" ,lastName:"Heritege" },
  { id:18, firstName:"Joséphine" ,lastName:"Keele" },
  { id:19, firstName:"Jú" ,lastName:"Kemwal" },
  { id:20, firstName:"Gaïa" ,lastName:"Karolczyk" },
  { id:21, firstName:"Régine" ,lastName:"MacTimpany" },
  { id:22, firstName:"Kallisté" ,lastName:"Matias" },
  { id:23, firstName:"Camélia" ,lastName:"Ebbetts" },
  { id:24, firstName:"Marie" ,lastName:"Rowsell" },
  { id:25, firstName:"Alizée" ,lastName:"MacLennan" },
  { id:26, firstName:"Nadège" ,lastName:"Pesticcio" },
  { id:27, firstName:"Véronique" ,lastName:"Troyes" },
  { id:28, firstName:"Hélène" ,lastName:"Amoore" },
  { id:29, firstName:"Andréanne" ,lastName:"Bouttell" },
  { id:30, firstName:"Thérèsa" ,lastName:"Gillon" },
  { id:31, firstName:"Mén" ,lastName:"Lyttle" },
  { id:32, firstName:"Adèle" ,lastName:"Gemson" },
  { id:33, firstName:"Stévina" ,lastName:"MacChaell" },
  { id:34, firstName:"Bénédicte" ,lastName:"Halston" },
  { id:35, firstName:"Océanne" ,lastName:"Vella" },
  { id:36, firstName:"Styrbjörn" ,lastName:"Errowe" },
  { id:37, firstName:"Märta" ,lastName:"Barfield" },
  { id:38, firstName:"Laurélie" ,lastName:"Precious" },
  { id:39, firstName:"Gaétane" ,lastName:"Mc Pake" },
  { id:40, firstName:"Marie-ève" ,lastName:"Ponsford" },
  { id:41, firstName:"Pénélope" ,lastName:"Yallop" },
  { id:42, firstName:"Méline" ,lastName:"Morecomb" },
  { id:43, firstName:"Annotée" ,lastName:"Britzius" },
  { id:44, firstName:"Kuí" ,lastName:"Caveill" },
  { id:45, firstName:"Maïlis" ,lastName:"Jeannaud" },
  { id:46, firstName:"Maï" ,lastName:"Baty" },
  { id:47, firstName:"Célia" ,lastName:"McGairl" },
  { id:48, firstName:"Laurène" ,lastName:"Ducker" },
  { id:49, firstName:"Néhémie" ,lastName:"Lusher" },
  { id:50, firstName:"Céline" ,lastName:"Speechly" },
  { id:51, firstName:"Edmée" ,lastName:"Dandy" },
  { id:52, firstName:"Sòng" ,lastName:"Teissier" },
  { id:53, firstName:"Marylène" ,lastName:"Bendon" },
  { id:54, firstName:"Judicaël" ,lastName:"Gatteridge" },
  { id:55, firstName:"Angélique" ,lastName:"Buddle" },
  { id:56, firstName:"Hélène" ,lastName:"Fennell" },
  { id:57, firstName:"Josée" ,lastName:"Reynard" },
  { id:58, firstName:"Loïs" ,lastName:"Diem" },
  { id:59, firstName:"Danièle" ,lastName:"Lovering" },
  { id:60, firstName:"Pal" ,lastName:"Zimmer" },
  { id:61, firstName:"Irène" ,lastName:"Piatkowski" },
  { id:62, firstName:"Josée" ,lastName:"Stot" },
  { id:63, firstName:"Kallisté" ,lastName:"Gregor" },
  { id:64, firstName:"Mélanie" ,lastName:"Adanet" },
  { id:65, firstName:"Marie-josée" ,lastName:"Blasetti" },
  { id:66, firstName:"Kévina" ,lastName:"Worcester" },
  { id:67, firstName:"Annotés" ,lastName:"Plowman" },
  { id:68, firstName:"Nuó" ,lastName:"Ricardot" },
  { id:69, firstName:"Åke" ,lastName:"McTrustie" },
  { id:70, firstName:"Estève" ,lastName:"Biscomb" },
  { id:71, firstName:"Léa" ,lastName:"Theriot" },
  { id:72, firstName:"Inès" ,lastName:"Trusler" },
  { id:73, firstName:"Garçon" ,lastName:"Abernethy" },
  { id:74, firstName:"Clémentine" ,lastName:"Staig" },
  { id:75, firstName:"Börje" ,lastName:"Shemelt" },
  { id:76, firstName:"Björn" ,lastName:"McArtan" },
  { id:77, firstName:"Eléa" ,lastName:"Tayloe" },
  { id:78, firstName:"Laurélie" ,lastName:"Scoterbosh" },
  { id:79, firstName:"Yú" ,lastName:"Croxley" },
  { id:80, firstName:"Lorène" ,lastName:"Reary" },
  { id:81, firstName:"Anaëlle" ,lastName:"Luter" },
  { id:82, firstName:"Maïwenn" ,lastName:"Wackly" },
  { id:83, firstName:"Cécile" ,lastName:"Cockerell" },
  { id:84, firstName:"Ruò" ,lastName:"Ingilson" },
  { id:85, firstName:"Bénédicte" ,lastName:"Bladesmith" },
  { id:86, firstName:"Aloïs" ,lastName:"Kemmet" },
  { id:87, firstName:"Lèi" ,lastName:"Droghan" },
  { id:88, firstName:"Camélia" ,lastName:"Chittenden" },
  { id:89, firstName:"Faîtes" ,lastName:"Girardy" },
  { id:90, firstName:"Lóng" ,lastName:"Balharrie" },
  { id:91, firstName:"Léa" ,lastName:"Laugharne" },
  { id:92, firstName:"Gaëlle" ,lastName:"Stair" },
  { id:93, firstName:"Anaël" ,lastName:"Rain" },
  { id:94, firstName:"Lèi" ,lastName:"Edsell" },
  { id:95, firstName:"Néhémie" ,lastName:"Stuckley" },
  { id:96, firstName:"Geneviève" ,lastName:"Eastabrook" },
  { id:97, firstName:"Sòng" ,lastName:"Tyzack" },
  { id:98, firstName:"Méline" ,lastName:"Rackstraw" },
  { id:99, firstName:"Anais" ,lastName:"Stapforth" },
  { id:100, firstName:"Görel" ,lastName:"Aizikovich"}
]

const shops = [
  { 
    name: "Paris I",
    transactions: [
      { id: 303020, clientId: 1, amount: 3200 },
      { id: 303020, clientId: 10, amount: 200 },
      { id: 130684, clientId: 4, amount: 568}, 
      { id: 761320, clientId: 30, amount: 99 },
      { id: 678984, clientId: 7, amount: 291 },
      { id: 344256, clientId: 86, amount: 853 },
      { id: 102267, clientId: 97, amount: 692 },
      { id: 845760, clientId: 34, amount: 148 },
      { id: 511574, clientId: 29, amount: 646 },
      { id: 730624, clientId: 56, amount: 967 },
      { id: 242281, clientId: 25, amount: 60 }
    ]
  },
  {
    name: "Paris II",
    transactions: [
      { id: 306442, clientId: 15, amount: 8014 },
      { id: 309011, clientId: 1, amount: 1705 },
      { id: 503201, clientId: 18, amount: 120 }
    ]
  },
  {
    name: "Lyon I",
    transactions: [
      { id: 679030, clientId: 90, amount: 882 },
      { id: 563980, clientId: 69, amount: 906 },
      { id: 131639, clientId: 24, amount: 827 },
      { id: 525731, clientId: 25, amount: 553 },
      { id: 602337, clientId: 96, amount: 91 },
      { id: 549745, clientId: 84, amount: 981 },
      { id: 411947, clientId: 2, amount: 770 }
    ]
  },

  {
    name: "Lyon II",
    transactions: [
      { id: 553369, clientId: 55, amount: 811 },
      { id: 460350, clientId: 7, amount: 331 },
      { id: 760705, clientId: 91, amount: 746 }, 
      { id: 133868, clientId: 12, amount: 59 }, 
      { id: 141384, clientId: 25, amount: 386 }, 
      { id: 862286, clientId: 33, amount: 758 } 
    ]
  },
    {
    name: "Lille",
    transactions: [
      { id: 715185, clientId: 23, amount: 508 },
      { id: 307611, clientId: 42, amount: 839 },
      { id: 282574, clientId: 27, amount: 242 },
      { id: 478831, clientId: 27, amount: 945 },
      { id: 887358, clientId: 51, amount: 401 },
      { id: 794893, clientId: 33, amount: 820 },
      { id: 543806, clientId: 37, amount: 787 }
    ]
  },
  {
    name: "Bordeaux",
    transactions: [
      { id: 729527, clientId: 17, amount: 600 },
      { id: 802502, clientId: 92, amount: 886 },
      { id: 511714, clientId: 80, amount: 934 },
      { id: 957908, clientId: 72, amount: 625 },
      { id: 665306, clientId: 91, amount: 376 },
      { id: 867410, clientId: 34, amount: 194 }
    ]
  }
]